module.exports = {
  bracketSpacing: true,
  jsxBracketSameLine: true,
  singleQuote: true,
  trailingComma: 'all',
  arrowParens: 'avoid',
  tabWidth: 2,
  printWidth: 120,
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '^&/app/(.*)$|^(&/app)',
    '^&/components/(.*)$|^(&/components$)',
    '^&/lib/(.*)$|^(&/lib)',
    '^&/public/(.*)$|^(&/public)',
    '',
    '^[./]',
  ],
  importOrderTypeScriptVersion: true,
  plugins: ['prettier-plugin-tailwindcss', '@ianvs/prettier-plugin-sort-imports'],
};
